M48
; DRILL file {KiCad 7.0.10-7.0.10~ubuntu22.04.1} date Chủ nhật, 20 Tháng 4 Năm 2025 11:35:06 +07
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-20T11:35:06+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10-7.0.10~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X67.691Y-55.575
X67.691Y-98.095
X116.027Y-77.216
M30
